create extension if not exists pgcrypto;

create table if not exists public.profile (
  id integer primary key default 1 check (id = 1),
  display_name text not null,
  subtitle text not null default '',
  bio text not null default '',
  avatar_url text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  icon text not null default 'globe',
  position integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  organization_id bigint references public.organizations(id) on delete set null,
  code text not null,
  visited_at timestamptz not null default now(),
  language text,
  browser text,
  os text,
  device text,
  country text,
  region text,
  city text,
  timezone text,
  browser_region text,
  referrer text,
  user_agent text
);

create table if not exists public.link_clicks (
  id bigint generated by default as identity primary key,
  link_id bigint references public.links(id) on delete set null,
  clicked_at timestamptz not null default now(),
  language text,
  browser text,
  os text,
  device text,
  country text,
  region text,
  city text,
  timezone text,
  browser_region text,
  referrer text,
  user_agent text
);

create index if not exists visits_organization_id_idx on public.visits(organization_id);
create index if not exists visits_code_idx on public.visits(code);
create index if not exists link_clicks_link_id_idx on public.link_clicks(link_id);

alter table public.visits add column if not exists country text;
alter table public.visits add column if not exists region text;
alter table public.visits add column if not exists city text;
alter table public.visits add column if not exists timezone text;
alter table public.visits add column if not exists browser_region text;
alter table public.link_clicks add column if not exists country text;
alter table public.link_clicks add column if not exists region text;
alter table public.link_clicks add column if not exists city text;
alter table public.link_clicks add column if not exists timezone text;
alter table public.link_clicks add column if not exists browser_region text;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-images',
  'profile-images',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into public.profile (id, display_name, subtitle, bio, avatar_url, updated_at)
values (
  1,
  'Cambodia Landmine Museum',
  'Museum, relief center, and education for a safer Cambodia',
  'Learn, visit, donate, and help us share why landmines still matter today.',
  'https://www.cambodialandminemuseum.org/wp-content/uploads/2026/06/clmm-logo-white-450x147.png',
  now()
)
on conflict (id) do nothing;

insert into public.links (title, url, icon, position, is_active, created_at, updated_at)
values
  ('Plan your visit', 'https://www.cambodialandminemuseum.org/plan-your-visit/', 'globe', 1, true, now(), now()),
  ('Buy museum tickets', 'https://www.cambodialandminemuseum.org/', 'globe', 2, true, now(), now()),
  ('Donate', 'https://www.cambodialandminemuseum.org/donate/', 'globe', 3, true, now(), now()),
  ('Instagram', 'https://www.instagram.com/cambodialandminemuseum/', 'globe', 4, true, now(), now())
on conflict do nothing;

insert into public.organizations (name, code, notes, created_at, updated_at)
values ('Hotel Angkor', '123', 'Example hotel for local QR tests.', now(), now())
on conflict (code) do nothing;

insert into public.organizations (name, code, notes, created_at, updated_at)
select
  'Organization ' || series.number,
  lpad(series.number::text, 4, '0'),
  'Physical QR pending assignment.',
  now(),
  now()
from generate_series(1, 50) as series(number)
on conflict (code) do nothing;
